name: Build and Release

on:
  push:
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: beep
            asset_name: beep-linux-x86_64

          # macOS
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: beep
            asset_name: beep-macos-x86_64
            
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: beep
            asset_name: beep-macos-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev pkg-config

    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        # macOS has CoreAudio built-in, no additional deps needed
        echo "No additional dependencies required for macOS"

    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.target }}

    - name: Build binary
      run: cargo build --release --target ${{ matrix.target }}

    - name: Strip binary (Unix)
      if: runner.os != 'Windows'
      run: |
        strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

    - name: Create archive (Unix)
      if: runner.os != 'Windows'
      run: |
        mkdir -p artifacts
        cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} artifacts/
        cp README.md artifacts/
        cp LICENSE artifacts/ 2>/dev/null || echo "LICENSE file not found, skipping"
        tar -czf ${{ matrix.asset_name }}.tar.gz -C artifacts .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: |
          ${{ matrix.asset_name }}.tar.gz
          ${{ matrix.asset_name }}.zip
        if-no-files-found: ignore

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev pkg-config
        
    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Run clippy
      run: cargo clippy -- -D warnings
      
    # - name: Check formatting
    #   run: cargo fmt -- --check

  release:
    name: Create Release
    needs: [build, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Display structure of downloaded files
      run: ls -la artifacts/
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*/*
        body: |
          ## Modern Beep ${{ github.ref_name }}
          
          ### Features
          - 🎵 Audio generation with customizable frequency and duration
          - 📱 Pushover notifications
          - 🌐 HTTP webhooks with JSON support
          - 🔊 Local and remote audio file playback
          - 📝 Verbose mode with `-v` flag
          
          ### Downloads
          - **Linux (glibc)**: `beep-linux-x86_64.tar.gz`
          - **macOS (Intel)**: `beep-macos-x86_64.tar.gz`
          - **macOS (Apple Silicon)**: `beep-macos-arm64.tar.gz`
          
          ### Installation
          ```bash
          # Extract and install
          tar -xzf beep-linux-x86_64.tar.gz
          sudo cp beep /usr/local/bin/
          
          # Or to user directory
          cp beep ~/.local/bin/
          ```
          
          ### Usage
          ```bash
          # Basic beep
          beep -f 800 -l 500
          
          # With notification
          beep -D "Process completed!" -t "Alert"
          
          # Verbose mode
          beep -v -f 440 -r 3 -d 200
          ```
          
          See [README.md](https://github.com/${{ github.repository }}/blob/main/README.md) for full documentation.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install cargo-audit
      run: cargo install cargo-audit
      
    - name: Run security audit
      run: cargo audit